// Additional authored sections for the ten industry insights. These are guidance, not client case studies.
export const industryInsightDetails: Record<string, string> = {
  "energy-ai-asset-intelligence-foundations": `
    <h2>The business challenge: different records describe the same asset</h2>
    <p>A compressor, pipeline segment, or field instrument may have an identifier in the maintenance system, another in telemetry, and a third in an inspection report. Before a predictive model can help, the team needs to know whether those records actually refer to the same equipment. Location, installation date, operating mode, and maintenance events all affect how a signal should be read. Missing or delayed data should be visible, not quietly filled with a plausible value.</p>
    <p>Asset intelligence is therefore a data-product problem as much as an AI problem. An asset register, source ownership, time alignment, and a definition of the decision being supported are the starting point. For remote operations, connectivity gaps and delayed uploads may be normal. A system should distinguish that condition from a genuine equipment anomaly.</p>
    <h2>A practical implementation path</h2>
    <p>Begin with one asset family and one decision, such as prioritizing inspections for a particular type of pump. Map the available sensor channels and work-order history. Check whether maintenance events are recorded consistently enough to serve as feedback. Build a baseline for normal operation across load and season rather than treating every change in vibration or temperature as a fault.</p>
    <p>Next, present an exception to the maintenance planner with the recent signal, the relevant asset history, and the reason it was prioritized. The planner can accept it, request more evidence, or dismiss it with an explanation. A field inspection closes the loop: the system records what technicians found and whether the alert led to useful action. This review process is more valuable than a model score viewed in isolation.</p>
    <h2>Data, safety, and governance considerations</h2>
    <p>Set permissions for operational and inspection data, document transformations, and retain a route back to original readings. Validate that a model trained on one configuration is not assumed to work unchanged after equipment replacement or sensor recalibration. Changes to maintenance priority should follow existing safety procedures and engineering approval. A low-confidence model output should never silently override a safety-critical rule.</p>
    <p>Evaluate the full workflow: alert burden, inspected findings, missed issues, and time from signal to decision. If staff cannot explain why a case was surfaced, improve the evidence view before expanding to more sites. <a href="/products/i-lakehouse">i-Lakehouse</a> describes a governed data foundation that can support this work; <a href="/enterprise-ai-solutions">enterprise AI solutions</a> covers maintenance decision support.</p>
    <h2>What to do next</h2>
    <p>Choose the asset and decision owner first, then inventory the available evidence and its quality. A bounded pilot should prove that teams can act on the signal and record the outcome. To discuss an energy asset workflow, <a href="/#connect">start a conversation with Turbo AI</a>.</p>`,
  "financial-services-ai-fraud-review": `
    <h2>The challenge behind an alert queue</h2>
    <p>Fraud monitoring operates under asymmetric costs. Missing a harmful event matters, but incorrectly interrupting a legitimate customer also has consequences. Rules may be deliberately broad, creating queues that mix obvious cases with weak signals. A new model should not simply replace the old score; it should help investigators see context, uncertainty, and the next review step.</p>
    <p>Case history is useful but imperfect. Past dispositions reflect the evidence, policies, and staffing available at the time. Treating every historical label as objective truth can reproduce earlier blind spots. Teams should examine how labels were created, how long data takes to arrive, and whether certain customer groups are overrepresented in manual reviews.</p>
    <h2>Design the investigation workflow</h2>
    <p>Start with a clearly defined queue, such as a class of payment anomalies. Join only approved signals: transaction sequence, account context, device or channel attributes where permitted, and prior case outcomes. Give investigators a concise timeline and show which facts are observed versus inferred. An alert should explain what changed from the normal pattern and which records support that view.</p>
    <p>The investigator then records a disposition and reason. If an action affects a customer, require the institution's established approval and communication process. The review interface should make it easy to correct false matches and flag missing data. Those corrections become part of model and rule evaluation, not a silent overwrite of the original case.</p>
    <h2>Evaluate the whole system</h2>
    <p>Before deployment, compare the proposed queue with a baseline on representative historical periods. Measure precision alongside recall, review workload, time to disposition, and customer friction. Test data delays and unusual events, because a model may behave differently during a new payment pattern or service outage. After release, monitor drift, investigator overrides, and whether alert volume shifts work to another team rather than reducing it.</p>
    <p>Privacy, security, and model governance are operational requirements. Define who can see a signal, how long it is kept, and how an incorrect outcome can be reviewed. The <a href="/data-engineering-ai-foundations">data engineering foundation</a> supports lineage and quality; <a href="/ai-governance-cybersecurity">AI governance and cybersecurity</a> addresses oversight, access, and monitoring.</p>
    <h2>A sensible first step</h2>
    <p>Pick one alert type with a named investigation owner and a measurable baseline. Validate whether better evidence and queue design help before increasing automation. To discuss a controlled fraud-review pilot, <a href="/#connect">contact Turbo AI</a>.</p>`,
  "insurance-claims-document-intelligence": `
    <h2>Why document volume is not the only problem</h2>
    <p>Claims files are assembled from many parties and at different stages. The same fact may appear in a form, an email, a repair estimate, and a policy schedule, sometimes with conflicting dates. A system that produces a fluent summary without showing its sources can make review faster but less reliable. The objective is to help a specialist locate and verify evidence, not to hide ambiguity.</p>
    <p>Document quality also varies. Scanned pages, handwriting, photographs, and forwarded email chains can defeat extraction. A workflow needs a way to record unreadable material, missing pages, and conflicting statements. It should not force every file into a complete-looking structured record.</p>
    <h2>A practical claims-file workflow</h2>
    <p>Define the claim types and documents in scope. At intake, classify a file, identify its version and source, and extract a small set of fields needed for routing. Show a reviewer the proposed field beside the relevant page or passage. Low-confidence extraction, inconsistencies, and policy mismatches move to an exception queue. Confirmed fields then populate a case view with an audit trail.</p>
    <p>Next, use approved policy retrieval to surface clauses that may be relevant to the file. The system should show effective dates, endorsements, and citations. It may draft questions for missing evidence or a summary of the file, but a claims professional checks the policy interpretation and any communication sent to a claimant. Coverage and payment decisions stay within the insurer's accountable process.</p>
    <h2>Evaluate usefulness and fairness</h2>
    <p>Track field-level accuracy, the rate of human corrections, missing-document identification, rework, and review time. Examine whether poor scan quality or a less common document type leads to systematically worse handling. Staff should be able to contest or correct a classification without losing the original record. Monitor whether a faster intake stage creates a backlog later in the claim.</p>
    <p>Security controls should cover personal information in source files, extracted fields, model requests, and retained logs. Data retention and access should follow the claim's purpose and applicable policy. <a href="/generative-ai-agentic-ai">Generative AI capabilities</a> can support cited retrieval and drafting; <a href="/ai-governance-cybersecurity">AI governance</a> provides the control framework.</p>
    <h2>Start with a bounded claim type</h2>
    <p>Choose a document-heavy step with known reviewers, representative samples, and a clear baseline. Prove that source-linked extraction makes the file easier to review before broadening the scope. <a href="/#connect">Talk with Turbo AI</a> about a claims-document workflow.</p>`,
  "healthcare-ai-knowledge-access": `
    <h2>The problem is trust in the answer</h2>
    <p>Healthcare staff often know the answer exists but not where the current version lives. A policy may have been superseded, a care pathway may apply only in one setting, and a procedure may be restricted to a particular role. A knowledge assistant that sounds certain without showing these boundaries adds risk rather than relieving the search burden.</p>
    <p>Start by separating administrative knowledge access from clinical decision-making. An assistant may help staff find a current form, referral process, or local operating procedure. That does not authorize it to diagnose a patient, select treatment, or replace a clinician's assessment. The intended audience, sources, and escalation route must be explicit.</p>
    <h2>Build a governed retrieval workflow</h2>
    <p>Choose a bounded set of approved documents with owners and revision dates. Respect source permissions at retrieval time, not only at login. Return a concise answer with citations and make the underlying passage easy to inspect. If two sources conflict, the document is out of date, or no authorized source answers the question, the assistant should abstain and point the user to the relevant owner.</p>
    <p>Test with real staff questions, including ambiguous language and questions outside scope. Evaluate whether the correct source appears, whether the answer accurately represents it, and whether users understand its limitations. Collect corrections through a managed process so outdated content can be fixed at the source instead of patched by prompting alone.</p>
    <h2>Privacy and operational safeguards</h2>
    <p>Use data minimization: a policy question generally does not need patient details. Where a workflow does involve personal information, define a purpose, role, retention period, audit trail, and approved deployment route. Test for inappropriate disclosure between roles and for prompt-injection attempts embedded in retrieved content. Accessibility and a human alternative are part of a usable service.</p>
    <p>Monitor retrieval failures, user corrections, and escalation volume after launch. A rising number of unanswered questions may indicate a content ownership problem rather than a model problem. The <a href="/generative-ai-agentic-ai">generative AI service</a> explains grounded assistants, while <a href="/ai-governance-cybersecurity">AI governance</a> covers access and oversight.</p>
    <h2>Begin with approved administrative knowledge</h2>
    <p>Select one audience and one maintained content set. Measure time spent finding guidance and the quality of cited answers before expansion. To explore a privacy-aware knowledge workflow, <a href="/#connect">start a conversation</a>.</p>`,
  "manufacturing-predictive-maintenance-workflow": `
    <h2>The maintenance decision is the product</h2>
    <p>A predictive model may detect a pattern, but the useful outcome is a technician knowing what asset to inspect and a planner knowing when to schedule it. Vibration, temperature, pressure, and other readings depend on load, material, season, and equipment configuration. A signal that ignores operating state can flood a team with false alarms or miss an important change.</p>
    <p>Historical work orders are also uneven. They may describe a repair without recording the original fault, or use different names for the same asset. Before training a model, reconcile identifiers and ask technicians which records reflect an actual failure. Their knowledge is essential for a credible baseline.</p>
    <h2>From telemetry to work order</h2>
    <p>Select one critical machine family and map sensors to assets. Record operating modes, maintenance events, and instrumentation changes. Establish a baseline for normal variation, then test whether an anomaly can be connected to a plausible inspection step. Present the alert with recent readings, comparable periods, and relevant service history. The system should state what it cannot infer.</p>
    <p>Let a maintenance planner review the case against production schedules, spare-parts availability, and safety requirements. If the team creates a work order, the technician records observations and the final action. Capture dismissed alerts as well; they are necessary for improving thresholds and identifying data quality issues. Automation should support the existing maintenance system rather than creating a parallel queue nobody owns.</p>
    <h2>Evaluation and governance</h2>
    <p>Review alert usefulness, missed failures, time to inspection, and the operational cost of acting on an alert. Compare outcomes across assets and modes. A model trained before a major equipment overhaul should be reevaluated afterward. Version data, features, and thresholds so an engineer can reconstruct why a recommendation appeared.</p>
    <p>Protect plant networks and restrict access to operational data. Define which system can recommend a task and which authorized person can approve maintenance. A predictive alert should not bypass lockout, safety, or engineering procedures. <a href="/data-engineering-ai-foundations">Data engineering</a> provides reliable pipelines, and <a href="/enterprise-ai-solutions">enterprise AI solutions</a> connects analytics to the work process.</p>
    <h2>Start small enough to learn</h2>
    <p>Choose a recurring, consequential maintenance question with a clear owner. Test against real technician decisions and refine the workflow before expanding to more lines. <a href="/#connect">Discuss a manufacturing pilot with Turbo AI</a>.</p>`,
  "construction-project-intelligence": `
    <h2>Why project data is difficult to use</h2>
    <p>Construction work changes as designs, conditions, and supply commitments evolve. A schedule activity may be linked to several drawings, an RFI, a subcontractor, and a piece of equipment, but those links are rarely stored together. When a field report identifies an issue, the manager may need to reconstruct its effect from multiple systems. That delay can matter more than the sophistication of any prediction.</p>
    <p>Current information is particularly important. A search result pointing to an obsolete drawing or unanswered RFI can be worse than no result. Every connected record should carry its project, location, activity, revision, timestamp, and owner where available. Missing relationships should be flagged rather than guessed.</p>
    <h2>A practical project-intelligence workflow</h2>
    <p>Choose a defined area or work package. Connect the near-term schedule to current drawings, open questions, site reports, material status, and equipment availability. Build a review view that shows the source of each update and the dependencies it may affect. Analytics can flag a delayed response or a likely resource clash, but the project manager confirms whether it truly threatens the plan.</p>
    <p>Use the weekly look-ahead meeting as the decision point. Show unresolved constraints, their owners, the evidence available, and the next action. After the meeting, record whether the issue was resolved, deferred, or incorrectly flagged. That feedback improves both the data model and the team's process. It also prevents the tool from becoming another dashboard disconnected from action.</p>
    <h2>Documents, safety, and governance</h2>
    <p>Retrieval can help find specifications or procedures, but answers need citations and revision dates. Contract interpretation, safety decisions, and site instructions remain with authorized professionals. Restrict access across project partners and retain the original record when an AI-generated summary is used. Avoid feeding sensitive commercial or personnel information into a tool without an approved purpose and deployment route.</p>
    <p>Evaluate time spent finding current information, age of unresolved constraints, quality of handoffs, and the number of false flags. <a href="/data-engineering-ai-foundations">Data engineering</a> supports the connected record; <a href="/generative-ai-agentic-ai">generative AI</a> can support controlled document retrieval.</p>
    <h2>Begin with one work package</h2>
    <p>Map the decisions made in a weekly planning cycle and the documents those decisions rely on. Test whether the connected view changes the conversation before expanding across a program. To explore a project workflow, <a href="/#connect">talk with Turbo AI</a>.</p>`,
  "retail-demand-customer-intelligence": `
    <h2>Why a single retail forecast is not enough</h2>
    <p>A product can appear to have weak demand because it was unavailable, poorly displayed, or excluded from a promotion. A digital click may not translate into local store demand. Returns and service complaints may reveal a product issue that sales alone cannot show. Retail intelligence needs to explain these differences rather than collapse them into one score.</p>
    <p>Data freshness matters as much as volume. Stock counts, transfers, online availability, and point-of-sale transactions are updated at different intervals. A replenishment recommendation made on an old inventory position can move goods to the wrong place. A useful system records when each source last changed and alerts users when confidence is low.</p>
    <h2>Connect the decision workflow</h2>
    <p>Start with a category and a small group of stores. Join sales, inventory, promotion, fulfilment, and returns data through stable product and location identifiers. Build a baseline forecast with uncertainty, then give merchants the reason for a proposed order or allocation change. Local managers should be able to note a nearby event or display change that the model cannot see.</p>
    <p>For customer service, retrieve approved policy and product knowledge alongside only the order context the employee is entitled to view. The assistant can suggest a response or next step, but the employee confirms it. Customer data should not be reused across marketing and service purposes without a valid basis and clear controls.</p>
    <h2>Measure the wider outcome</h2>
    <p>Track availability, stockouts, excess inventory, forecast error, returns, and service resolution together. Improving one measure can worsen another; for example, a forecast that minimizes stock may create missed sales or poor fulfilment. Review overrides and the reasons behind them, then update the data or process where staff repeatedly see a blind spot.</p>
    <p>Role-based access, consent, retention, and data lineage must be designed into the platform. <a href="/enterprise-ai-solutions">Enterprise AI solutions</a> covers customer and supply-chain intelligence, while <a href="/products/i-lakehouse">i-Lakehouse</a> describes the governed data foundation.</p>
    <h2>Choose a bounded retail decision</h2>
    <p>Pick one replenishment, service, or assortment decision with an accountable team. Establish what information staff currently use and where it fails. Test whether the new view improves that decision before scaling. <a href="/#connect">Discuss a retail use case</a>.</p>`,
  "logistics-exception-management-ai": `
    <h2>The problem with more alerts</h2>
    <p>Logistics networks produce a continuous stream of status changes. A late scan, a delayed vessel, and a supplier change may all refer to the same order, but an alerting system can present them as separate emergencies. Conversely, a quiet feed can hide a missing update. Exception management begins by establishing what is known, what is delayed, and which customer or production commitment is exposed.</p>
    <p>Impact is contextual. A delay may be harmless when alternate stock is available, or serious when a single component blocks a planned production run. A priority model should show the relevant commitment, stock position, lead time, and source freshness so a planner can challenge the conclusion.</p>
    <h2>A practical exception workflow</h2>
    <p>For a bounded lane or product family, connect orders, shipment milestones, inventory, supplier notices, and delivery promises. Assign stable identifiers and timestamps. Group events into a case and calculate the likely impact using documented rules or models. Present alternatives, such as reallocating stock or contacting a customer, but do not assume the system has authority to make a commercial commitment.</p>
    <p>The planner reviews the case, chooses an action, and records why. A case owner should be visible when the work passes from procurement to transport or fulfilment. After resolution, capture whether the suggested priority was useful and whether the chosen action reduced disruption. That feedback can improve ranking even when a forecast remains imperfect.</p>
    <h2>Data and governance considerations</h2>
    <p>Different partners provide feeds with different reliability. Monitor lateness, duplicates, and missing events. Keep contractual data and customer details limited to authorized roles. If automation is introduced later, define approval thresholds and rollback for any external action. An exception system should be able to explain the data and rule that led to a recommendation.</p>
    <p>Measure time to identify an exposed commitment, duplicate-alert burden, action handoffs, and avoidable disruption. <a href="/data-engineering-ai-foundations">Data engineering</a> helps create a trustworthy event foundation; <a href="/products/adrs">ADRS</a> illustrates a controlled detection-to-response pattern.</p>
    <h2>Start with a real planner queue</h2>
    <p>Observe one exception process end to end before building a model. Define the owner, acceptable latency, and evidence needed for action. To explore a supply-chain workflow, <a href="/#connect">contact Turbo AI</a>.</p>`,
  "telecom-network-incident-triage": `
    <h2>Why network alarms need context</h2>
    <p>A fault in one network element may trigger many alarms elsewhere. Without topology, timing, and recent change history, a triage system can group unrelated issues or point to a downstream symptom. Operators also need to know which services and customers may be affected before assigning priority. Alarm count alone is a poor proxy for impact.</p>
    <p>Telecom data is distributed across monitoring, inventory, ticketing, and service systems. Those sources can disagree about asset state or update at different rates. The incident view should make data freshness and uncertain mappings visible. A plausible automated explanation should never hide a broken topology record.</p>
    <h2>Build a reviewable incident timeline</h2>
    <p>Begin with a defined network domain. Link telemetry to assets and dependencies, add approved change records, and map services to likely affected elements. Group alarms into candidate incidents using topology and time windows. Show the operator which events led to the grouping, the earliest relevant signal, and any conflicting evidence.</p>
    <p>The operator can confirm, split, or merge the candidate incident, then assign a response using established procedures. Field teams receive an approved asset history and current runbook rather than an opaque model instruction. When the issue is resolved, record cause, action, and whether the initial grouping helped. These corrections improve both the topology data and triage logic.</p>
    <h2>Security and measurement</h2>
    <p>Keep operational tools behind role-based permissions. A model that summarizes an incident does not need broad write access to network configuration. If remediation automation is considered, use explicit approval, narrow tool rights, and tested rollback. Preserve the original alarm and change records for post-incident review.</p>
    <p>Evaluate duplicate-alert reduction, time to form a credible hypothesis, missed dependencies, handoff quality, and incorrect groupings. Compare results across routine incidents and high-volume events. <a href="/cloud-infrastructure-ai-compute">Cloud and infrastructure capabilities</a> provide the operating foundation; <a href="/products/adrs">ADRS</a> shows a detection-to-response workflow.</p>
    <h2>Begin with one incident family</h2>
    <p>Choose an alarm pattern with known topology and documented resolution. Validate the evidence view with operators before widening coverage. To discuss a network triage pilot, <a href="/#connect">start a conversation</a>.</p>`,
  "data-centre-capacity-intelligence": `
    <h2>Capacity is a set of constraints</h2>
    <p>Space is only one input to a data-centre placement decision. A rack may appear available while its power feed has little headroom or the surrounding cooling zone cannot support the proposed load. Network connectivity, resilience requirements, maintenance access, and planned changes also matter. A useful capacity system must show the constraint that limits a placement, not simply a percentage of free floor space.</p>
    <p>Asset records drift as hardware moves, fails, or is replaced. Sensor values are time-dependent and sometimes missing. Before forecasting, teams need a consistent mapping among facility, room, rack, device, power path, and service. Each proposed capacity figure should have a timestamp and a source that an engineer can inspect.</p>
    <h2>A planning workflow beyond dashboards</h2>
    <p>Start with one room or cluster. Connect the current asset inventory, rack layout, measured power, cooling and environmental data, incident history, and planned workloads. Validate that these sources describe the same physical configuration. Then compare a proposed workload against power, cooling, space, and resilience limits. Present feasible options with assumptions and uncertainty rather than automatically selecting a rack.</p>
    <p>An infrastructure planner reviews the scenario with facilities and IT teams. They can account for maintenance windows, future reservations, and constraints the data does not yet capture. After a placement or upgrade, record actual utilization and any incident. This feedback makes the next forecast more credible and highlights outdated inventory.</p>
    <h2>Monitoring, governance, and response</h2>
    <p>When an alarm appears, link it to affected assets, power or cooling dependencies, and recent changes. Keep an operator responsible for validating impact and choosing an intervention. Changes to facility controls or compute placement should follow approved procedures and permissions. The data platform should preserve provenance for measurements, forecasts, and decisions.</p>
    <p>Measure forecast accuracy, constraint violations caught during planning, inventory corrections, and incident handoff quality. <a href="/products/dci-360">DCI 360</a> focuses on an integrated infrastructure view, while <a href="/cloud-infrastructure-ai-compute">cloud and AI compute services</a> address workload and platform planning.</p>
    <h2>Start with one capacity question</h2>
    <p>Choose a planned deployment or expansion and identify the decisions and data owners involved. Validate the physical inventory before modelling scenarios. To explore a data-centre capacity workflow, <a href="/#connect">contact Turbo AI</a>.</p>`,
};

export const industryInsightFollowUps: Record<string, string> = {
  "energy-ai-asset-intelligence-foundations": `
    <h2>Questions for an asset-intelligence pilot</h2>
    <p>Ask which decision currently waits on missing information. Is it an inspection route, a maintenance window, or a production constraint? List the records an engineer uses today and the time it takes to assemble them. If equipment identifiers do not align, correct that mapping before treating a predictive score as actionable. Sample periods of normal and abnormal operation should include changes in load, weather, and maintenance state.</p>
    <p>Set an explicit standard for an alert: the asset, the observed change, the source readings, a comparison period, and a named reviewer. Agree what happens when a sensor fails or an inspection contradicts the model. A pilot should test the entire handoff into maintenance planning, not just offline model accuracy. Operational teams should be able to explain a decision from the saved evidence months later.</p>
    <p>Expansion to another asset class is a new validation exercise. Different failure modes, data coverage, and response options may change the appropriate threshold. Record the costs of inspection and missed issues with the asset owner, then choose an evaluation measure that reflects the real decision. That discipline makes the analytics useful even if the first model is simple.</p>`,
  "financial-services-ai-fraud-review": `
    <h2>Questions before changing a live queue</h2>
    <p>Identify who owns the alert policy and who can approve a customer-facing action. Document which existing rules are mandatory controls and which are candidates for prioritization. A model should be tested beside the current process before it changes the queue. Compare the cases it would raise or suppress, including cases that investigators later overturned. This exposes whether apparent efficiency is merely shifting risk.</p>
    <p>Review how investigators record outcomes. If labels such as confirmed fraud, unresolved, and customer error are conflated, training and measurement will be misleading. Keep the model's explanation short enough for use in a case review but detailed enough to inspect the supporting events. Preserve the original transaction sequence and any subsequent correction, not just a final score.</p>
    <p>Finally, plan for unusual operating periods. New payment products, holidays, outages, and changes in customer behaviour can alter the baseline. Monitor alert distribution and customer complaints after release; give investigators a fast route to flag a new failure mode. A controlled rollback is part of responsible deployment, not evidence that the project failed.</p>`,
  "insurance-claims-document-intelligence": `
    <h2>Questions for the claims team</h2>
    <p>Which document types create the most review effort, and why? A high-volume form with consistent fields may be a better starting point than a complex file where every case differs. Ask reviewers which facts they copy repeatedly, which ones require interpretation, and which missing items cause rework. These answers determine where extraction can help and where human judgment must remain central.</p>
    <p>Build a representative evaluation set that includes poor scans, changed templates, handwritten notes, and multiple policy versions. Measure not only whether a field was extracted, but whether the reviewer could verify it quickly from the cited source. When two records disagree, the system should present the conflict rather than choose a fluent but unsupported resolution.</p>
    <p>Operational adoption needs a correction path. If staff fix a field, keep that edit with the identity, time, and reason permitted by the insurer's process. Review recurring corrections to improve templates, intake instructions, or source quality. A document workflow is valuable when it makes a claim easier to understand and hand over, not merely when it processes pages faster.</p>`,
  "healthcare-ai-knowledge-access": `
    <h2>Questions for content owners</h2>
    <p>Who approves a policy, and how does the system learn that it has changed? A retrieval pilot should start with a manageable collection that has named owners and a process for removing outdated versions. Test questions from different roles and locations, because the same answer may not apply across departments. A correct answer from an unauthorized document is still a failure.</p>
    <p>Observe how staff use citations. Can they reach the source quickly, see its effective date, and tell whether it applies to their setting? If users ignore the citation, improve the interface and training before relying on disclaimers. Include questions that have no answer in the approved collection; the assistant should abstain clearly rather than invent a procedure.</p>
    <p>Post-launch review should include content gaps and escalation outcomes. Repeated questions without a reliable source reveal a documentation problem that the organization must solve. For a sensitive workflow, privacy and clinical governance teams should define boundaries in advance. Expand only when the initial audience can consistently identify what the assistant knows and when to seek a qualified person.</p>`,
  "manufacturing-predictive-maintenance-workflow": `
    <h2>Questions to ask the plant team</h2>
    <p>Which equipment stops are most disruptive, and which could realistically have been prevented by earlier inspection? Not every failure has a detectable precursor. Ask technicians which sensor changes they consider meaningful and what operating modes produce harmless variation. Review work-order quality; an unstructured repair note may not support a precise training label without validation.</p>
    <p>Map the alert to a practical decision. The planner needs lead time to acquire parts, schedule a safe stop, and coordinate production. A model that signals an issue after that window closes may be statistically accurate but operationally unhelpful. Define the information required on a work item and the person who can approve it. Capture reasons for overrides so thresholds can be revisited with engineering evidence.</p>
    <p>Compare the pilot with ordinary maintenance planning across a representative period. Include false alarms, missed faults, technician effort, and any disruption caused by extra inspections. If the plant changes equipment or sensors, document whether the old baseline still applies. The aim is a dependable decision process that staff can operate and improve, not a permanent model left unattended.</p>`,
  "construction-project-intelligence": `
    <h2>Questions for a project pilot</h2>
    <p>Choose a work package where decisions routinely wait on documents or status updates. Ask a superintendent and planner to walk through a recent constraint: when was it first known, where was it recorded, and who had to act? That story reveals the identifiers and handoffs a connected view needs. Do not assume every document system contains the current revision.</p>
    <p>Define the boundary between a signal and an instruction. Analytics might show that an RFI is overdue or an equipment booking conflicts with scheduled work. The manager still checks site conditions, contractual obligations, and safety requirements. A useful interface displays the source, owner, date, and next review point. It should make unresolved assumptions visible at the planning meeting.</p>
    <p>Measure whether the pilot reduces time spent reconciling information and whether issues are assigned earlier. Track false flags and missing records, because they point to data stewardship needs. Expansion to another site should include a review of naming conventions, partner access, and document governance; construction programs rarely share a perfect data model by default.</p>`,
  "retail-demand-customer-intelligence": `
    <h2>Questions for merchants and store teams</h2>
    <p>Which decisions are repeated each week, and where does local knowledge override the central forecast? An effective pilot lets a merchant see the projected demand, current stock, upcoming promotion, and uncertainty in one view. Ask stores to record why they disagree with an allocation proposal. Those notes can reveal events or data gaps that the model cannot observe.</p>
    <p>Distinguish unmet demand from low demand. An item that was unavailable cannot generate sales, so historical transactions alone can understate its potential. Returns, substitutions, and online searches may add context, but each signal needs its own quality and privacy assessment. Reconcile product and location identifiers before joining digital and store data.</p>
    <p>Evaluate outcomes across several measures. A change that improves inventory turnover may increase stockouts; a service assistant that reduces handle time may lower resolution quality. Include staff overrides and customer feedback in the review. Once the workflow is reliable for a bounded category, test whether the same logic holds for other products and locations rather than assuming it will transfer unchanged.</p>`,
  "logistics-exception-management-ai": `
    <h2>Questions for planners and partners</h2>
    <p>Ask which exceptions consume the most attention and which ones are genuinely costly. A lane may have many late scans but few late deliveries, while a low-volume part may halt production when delayed. Define priority using the commitment and available alternatives, not an arbitrary count of alerts. Planners should be able to see the last confirmed event and the source of each status update.</p>
    <p>Test data delays deliberately. If a carrier feed stops, does the system show an unknown state or treat the last scan as current? How are duplicate messages and corrected milestones handled? These failure cases matter more than a polished demonstration with complete data. Record a case owner and handoff history so people can coordinate across procurement, transport, and fulfilment.</p>
    <p>Before automating an external action, decide who may approve a reroute, promise date, or supplier message. The risk of a wrong action is different from the risk of a wrong recommendation. Begin by measuring whether a better exception view helps staff recognize exposed commitments earlier. Add automation only where permissions, reversibility, and auditability are clear.</p>`,
  "telecom-network-incident-triage": `
    <h2>Questions for the NOC</h2>
    <p>Which incident patterns repeatedly generate duplicate alarms, and what evidence do operators use to identify the initiating fault? Map those clues to telemetry, topology, and change records. A first pilot should cover a domain with reasonably current dependency data. If the inventory is stale, improving it may create more value than a more complex correlation model.</p>
    <p>Show the operator why events were grouped and how service impact was estimated. Allow a quick split or merge when the proposed incident is wrong. A plausible root-cause label should be accompanied by timing and dependency evidence, and it should never directly authorize a network change. The field handoff should include the validated asset state and current runbook.</p>
    <p>Evaluate both routine and high-volume events. During an alarm storm, the triage view should remain responsive and indicate when data has stopped arriving. Review false groupings, missed dependencies, and whether the operator reached a credible hypothesis sooner. Incident review then feeds corrections back into topology, data quality checks, and procedures, not merely a model retraining queue.</p>`,
  "data-centre-capacity-intelligence": `
    <h2>Questions for capacity planners</h2>
    <p>Ask which constraint most often surprises a placement decision: space, power, cooling, network, or maintenance access. Use a recent proposed workload to trace how teams established available capacity. Compare inventory records with the physical estate and identify who owns corrections. A dashboard value without a reliable rack and feed mapping should be treated as provisional.</p>
    <p>Define a scenario with its assumptions: expected power draw, redundancy requirement, cooling envelope, growth allowance, and deployment date. Show where each input came from and how old it is. Facilities and IT teams can then discuss feasible placements or required upgrades. The tool supports that conversation; it does not approve a change to electrical or cooling systems.</p>
    <p>After implementation, compare predicted and measured utilization and record unexpected constraints. Review incident history to see whether the chosen placement changed operational risk. A pilot that improves inventory accuracy and cross-team decisions is useful even before advanced forecasting. Expansion should follow a repeatable change-record process so the model remains aligned with the physical estate.</p>`,
};

export const industryInsightChecks: Record<string, string> = {
  "energy-ai-asset-intelligence-foundations": "For every suggested inspection, ask whether the alert would have changed the team's plan and whether the evidence was available early enough. If the answer is no, refine the decision boundary before investing in a more complex model. Reliable identifiers, source freshness, and a technician feedback route often create the first useful improvement.",
  "financial-services-ai-fraud-review": "A launch review should include investigators, risk owners, privacy specialists, and the customer-service team. Each group sees a different cost of a wrong priority. Agree how to examine disputed cases and what would trigger a pause or rollback. This governance is most useful when it is built into normal case handling rather than a separate annual assessment.",
  "insurance-claims-document-intelligence": "Ask reviewers to compare a prepared file with their ordinary process. Did the extraction reveal all relevant source passages, and was it easy to challenge a proposed field? Test rare policy variations and incomplete submissions. A fast average result is not enough if difficult claims become harder to understand or are sent to the wrong specialist.",
  "healthcare-ai-knowledge-access": "A practical acceptance test should include current policy questions, outdated wording, ambiguous requests, and questions the collection cannot answer. Staff should be able to see what the assistant retrieved and report a problem without exposing patient information. Give content owners a schedule for reviewing corrections so the knowledge base remains trustworthy after launch.",
  "manufacturing-predictive-maintenance-workflow": "Make the alert review part of the normal maintenance meeting. Engineers and technicians can inspect examples of useful, missed, and distracting signals together. Track whether a proposed inspection fit the production plan and whether spare parts were available. These operational constraints determine whether predictive maintenance changes outcomes more than an offline accuracy score does.",
  "construction-project-intelligence": "A useful acceptance test follows a single issue from site observation through planning, decision, and closure. Can every participant find the current document, named owner, and next action? Check whether partner permissions hide needed information or expose too much. The project record should preserve a decision's source even when schedules and drawings are revised later.",
  "retail-demand-customer-intelligence": "A pilot should compare recommendations with merchant decisions, not treat every override as a mistake. Some overrides capture local knowledge; others reveal a missing promotion or inventory correction. Document the reason and test whether adding that context improves the next cycle. Evaluate the result across stores with different demand patterns before expanding the forecast.",
  "logistics-exception-management-ai": "Observe a planner's shift and record which alerts lead to a real intervention. If several events refer to one disruption, present a single case with the sequence intact. If the status is uncertain, say so. The acceptance test is whether the team can reach a better decision with less reconstruction and a clearer handoff to partners.",
  "telecom-network-incident-triage": "Include an operator review of cases where the suggested grouping was wrong. Was the topology stale, did timing mislead the model, or did two faults occur together? Correct the relevant source or rule and preserve the case for future evaluation. This is especially important when the network changes faster than the inventory or monitoring configuration.",
  "data-centre-capacity-intelligence": "Ask facilities and IT planners to compare a proposed placement with their usual approval process. Can the tool show the limiting constraint and the age of its supporting measurement? Record any manual adjustment to power, cooling, or reservation assumptions. Those corrections should update the capacity record so the next decision starts from the current estate.",
};
